# Generated by Django 5.2.17 on 2026-10-05 12:41

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credentials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitProviderConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("web_url", models.URLField(max_length=500)),
                ("api_url", models.URLField(max_length=500)),
                ("app_id", models.CharField(blank=True, max_length=64)),
                ("app_slug", models.CharField(blank=True, max_length=200)),
                ("app_name", models.CharField(blank=True, max_length=200)),
                ("app_html_url", models.URLField(blank=True, max_length=500)),
                ("client_id", models.CharField(blank=True, max_length=200)),
                ("encrypted_private_key", models.TextField(blank=True)),
                ("encrypted_webhook_secret", models.TextField(blank=True)),
                ("encrypted_client_secret", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.BigIntegerField()),
                ("account_login", models.CharField(max_length=200)),
                ("account_type", models.CharField(blank=True, max_length=32)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="repositories.gitproviderconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.BigIntegerField()),
                ("full_name", models.CharField(max_length=300)),
                ("default_branch", models.CharField(blank=True, max_length=255)),
                ("private", models.BooleanField(default=True)),
                ("html_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("removed", "Removed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="repositories.installation",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="RepositorySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_review", models.BooleanField(default=True)),
                ("review_drafts", models.BooleanField(default=False)),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Overrides the credential's default model.",
                        max_length=200,
                    ),
                ),
                (
                    "ignore_patterns",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("replace_default_ignores", models.BooleanField(default=False)),
                ("custom_instructions", models.TextField(blank=True, max_length=4000)),
                (
                    "min_severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("min_confidence", models.FloatField(default=0.5)),
                ("max_inline_comments", models.PositiveIntegerField(default=25)),
                ("max_changed_lines", models.PositiveIntegerField(default=2000)),
                ("max_files", models.PositiveIntegerField(default=100)),
                (
                    "max_input_tokens",
                    models.PositiveIntegerField(
                        default=150000, help_text="Hard cap per review run."
                    ),
                ),
                (
                    "chunk_tokens",
                    models.PositiveIntegerField(
                        default=12000, help_text="Target diff tokens per LLM request."
                    ),
                ),
                ("post_when_no_findings", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repository_settings",
                        to="credentials.llmcredential",
                    ),
                ),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="repositories.repository",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="installation",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_id"),
                name="uniq_installation_external_id",
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["external_id"], name="repositorie_externa_b1dccb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("installation", "external_id"),
                name="uniq_repository_external_id",
            ),
        ),
    ]
