# Generated by Django 5.2.17 on 2026-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorysettings",
            name="check_runs",
            field=models.BooleanField(
                default=True, help_text="Report a GitHub check run per review."
            ),
        ),
        migrations.AddField(
            model_name="repositorysettings",
            name="gate_severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("info", "Info"),
                ],
                default="",
                help_text="Fail the check run when a finding at or above this severity is reported (empty = never).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="repositorysettings",
            name="profile",
            field=models.CharField(
                choices=[
                    ("strict", "Strict"),
                    ("balanced", "Balanced"),
                    ("lenient", "Lenient"),
                    ("security", "Security-focused"),
                ],
                default="balanced",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="repositorysettings",
            name="review_on_push",
            field=models.BooleanField(
                default=True, help_text="Review new commits pushed to open PRs."
            ),
        ),
    ]
