# Generated by Django 5.2.17 on 2026-10-06 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0002_settings_profile_push_checks"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorysettings",
            name="base_branch_patterns",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="Only auto-review PRs whose base branch matches one of these globs (empty = all).",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="repositorysettings",
            name="rules",
            field=models.JSONField(
                blank=True, default=list, help_text="Structured review rules (RE-14)."
            ),
        ),
    ]
