# Generated by Django 5.2.17 on 2026-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0003_branch_filters_and_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorysettings",
            name="suggest_tests",
            field=models.BooleanField(
                default=True, help_text="Ask for tests when source changes lack them."
            ),
        ),
    ]
