# Generated by Django 5.2.17 on 2026-10-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0004_suggest_tests"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitproviderconnection",
            name="encrypted_access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="webhook_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
