# Generated by Django 5.2.17 on 2026-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0005_gitlab"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorysettings",
            name="extended_context",
            field=models.BooleanField(
                default=True,
                help_text="Send imports and the enclosing function of each change to the LLM.",
            ),
        ),
    ]
