# Generated by Django 5.2.17 on 2026-10-06 11:24

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repositories", "0004_suggest_tests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("encrypted_url", models.TextField(blank=True)),
                (
                    "encrypted_secret",
                    models.TextField(
                        blank=True, help_text="HMAC signing secret (webhook channels)."
                    ),
                ),
                ("url_hint", models.CharField(blank=True, max_length=120)),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("review.high_risk", "High-risk pull request"),
                                ("review.failed", "Review failed"),
                                ("budget.threshold", "LLM budget threshold reached"),
                                ("digest.weekly", "Weekly digest"),
                            ],
                            max_length=32,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("min_risk", models.PositiveSmallIntegerField(default=60)),
                (
                    "min_severity",
                    models.CharField(blank=True, default="critical", max_length=16),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repositories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Empty means every repository.",
                        related_name="+",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=32)),
                ("dedup_key", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=500)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notificationchannel",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="notificatio_created_f0c306_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "event", "dedup_key"),
                        name="uniq_notification_delivery",
                    )
                ],
            },
        ),
    ]
