# Generated by Django 5.2.17 on 2026-10-06 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("target_type", models.CharField(blank=True, max_length=32)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("target_label", models.CharField(blank=True, max_length=300)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__59bbff_idx",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION audit_auditevent_append_only() RETURNS trigger AS $$
            BEGIN
                -- Allow only ON DELETE SET NULL of the actor; every other change is rejected.
                IF NEW.actor_id IS NOT NULL
                   OR ROW(NEW.id, NEW.created_at, NEW.actor_email, NEW.action, NEW.target_type, NEW.target_id,
                          NEW.target_label, NEW.ip, NEW.user_agent, NEW.metadata)
                      IS DISTINCT FROM
                      ROW(OLD.id, OLD.created_at, OLD.actor_email, OLD.action, OLD.target_type, OLD.target_id,
                          OLD.target_label, OLD.ip, OLD.user_agent, OLD.metadata)
                THEN
                    RAISE EXCEPTION 'audit events are append-only';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER audit_auditevent_append_only BEFORE UPDATE ON audit_auditevent
                FOR EACH ROW EXECUTE FUNCTION audit_auditevent_append_only();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS audit_auditevent_append_only ON audit_auditevent;
            DROP FUNCTION IF EXISTS audit_auditevent_append_only();
            """,
        ),
    ]
