# Generated by Django 5.2.17 on 2026-10-05 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repositories", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=16)),
                ("delivery_id", models.CharField(max_length=100)),
                ("event", models.CharField(max_length=64)),
                ("action", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=300)),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="repositories.repository",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reviews.reviewrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "delivery_id"), name="uniq_webhook_delivery"
                    )
                ],
            },
        ),
    ]
