# Generated by Django 5.2.17 on 2026-10-05 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("openai_compatible", "OpenAI-compatible"),
                            ("fake", "Demo"),
                        ],
                        max_length=32,
                    ),
                ),
                ("base_url", models.URLField(blank=True, max_length=500)),
                ("encrypted_secret", models.TextField(blank=True)),
                ("last4", models.CharField(blank=True, max_length=4)),
                ("default_model", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("revoked", "Revoked"),
                        ],
                        default="valid",
                        max_length=16,
                    ),
                ),
                ("status_message", models.CharField(blank=True, max_length=500)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "monthly_budget_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
