# Generated by Django 5.2.17 on 2026-10-06 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def install_default_prices(apps, schema_editor):
    from apps.credentials.pricing import install_defaults

    install_defaults(apps.get_model("credentials", "ModelPrice"))


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="First day of the month (UTC).")),
                ("threshold", models.PositiveSmallIntegerField()),
                ("spent_usd", models.DecimalField(decimal_places=6, max_digits=12)),
                ("budget_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_alerts",
                        to="credentials.llmcredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("credential", "month", "threshold"),
                        name="uniq_budget_alert",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("model_prefix", models.CharField(blank=True, max_length=200)),
                (
                    "input_usd_per_mtok",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "output_usd_per_mtok",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Shipped with Reviewbot rather than added by an admin.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "model_prefix"],
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "model_prefix"), name="uniq_model_price")
                ],
            },
        ),
        migrations.RunPython(install_default_prices, migrations.RunPython.noop),
    ]
