# Generated by Django 5.2.17 on 2026-10-05 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credentials", "0001_initial"),
        ("repositories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("author_login", models.CharField(blank=True, max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("merged", "Merged"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("is_draft", models.BooleanField(default=False)),
                ("base_ref", models.CharField(blank=True, max_length=255)),
                ("head_ref", models.CharField(blank=True, max_length=255)),
                ("head_sha", models.CharField(max_length=64)),
                ("html_url", models.URLField(blank=True, max_length=500)),
                ("last_reviewed_sha", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("webhook", "Webhook"), ("manual", "Manual")],
                        max_length=16,
                    ),
                ),
                ("head_sha", models.CharField(max_length=64)),
                ("base_sha", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, max_length=64)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fetch_diff", "Fetching diff"),
                            ("filter", "Filtering files"),
                            ("chunk", "Chunking"),
                            ("llm", "Calling LLM"),
                            ("aggregate", "Aggregating findings"),
                            ("post_comments", "Posting comments"),
                            ("done", "Done"),
                            ("timeout", "Timed out"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=200)),
                ("settings_snapshot", models.JSONField(default=dict)),
                ("files_reviewed", models.JSONField(default=list)),
                ("files_ignored", models.JSONField(default=list)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("chunks_failed", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("provider_review_id", models.CharField(blank=True, max_length=64)),
                ("provider_review_url", models.URLField(blank=True, max_length=500)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_runs",
                        to="credentials.llmcredential",
                    ),
                ),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_runs",
                        to="reviews.pullrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LLMUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=200)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "OK"), ("error", "Error")], max_length=8
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "credential",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage",
                        to="credentials.llmcredential",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="repositories.repository",
                    ),
                ),
                (
                    "review_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage",
                        to="reviews.reviewrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("path", models.CharField(max_length=1000)),
                ("line_start", models.PositiveIntegerField(blank=True, null=True)),
                ("line_end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "anchored",
                    models.BooleanField(
                        default=False,
                        help_text="Line is part of the diff and can be commented on.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("security", "Security"),
                            ("performance", "Performance"),
                            ("maintainability", "Maintainability"),
                            ("style", "Style"),
                            ("test", "Test"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=16,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("title", models.CharField(max_length=300)),
                ("body", models.TextField()),
                ("suggestion", models.TextField(blank=True)),
                (
                    "post_status",
                    models.CharField(
                        choices=[
                            ("posted", "Posted inline"),
                            ("in_summary", "Listed in summary"),
                            ("below_threshold", "Below severity threshold"),
                            ("low_confidence", "Low confidence"),
                            ("duplicate", "Already posted on this PR"),
                            ("cap_exceeded", "Inline comment cap reached"),
                            ("not_posted", "Not posted (review failed)"),
                        ],
                        default="not_posted",
                        max_length=24,
                    ),
                ),
                ("provider_comment_id", models.CharField(blank=True, max_length=64)),
                ("provider_comment_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "review_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="reviews.reviewrun",
                    ),
                ),
            ],
            options={
                "ordering": ["path", "line_start", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.UniqueConstraint(
                fields=("repository", "number"), name="uniq_pull_request_number"
            ),
        ),
        migrations.AddIndex(
            model_name="llmusage",
            index=models.Index(
                fields=["credential", "created_at"],
                name="reviews_llm_credent_583043_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmusage",
            index=models.Index(
                fields=["repository", "created_at"],
                name="reviews_llm_reposit_f33297_idx",
            ),
        ),
    ]
