# Generated by Django 5.2.17 on 2026-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrun",
            name="check_run_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="reviewrun",
            name="compare_base_sha",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="reviewrun",
            name="incremental",
            field=models.BooleanField(
                default=False,
                help_text="Only changes since compare_base_sha were reviewed.",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="post_status",
            field=models.CharField(
                choices=[
                    ("posted", "Posted inline"),
                    ("in_summary", "Listed in summary"),
                    ("below_threshold", "Below severity threshold"),
                    ("low_confidence", "Low confidence"),
                    ("duplicate", "Already posted on this PR"),
                    ("cap_exceeded", "Inline comment cap reached"),
                    ("not_posted", "Not posted (review failed)"),
                    ("category_filtered", "Category excluded by profile"),
                ],
                default="not_posted",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="reviewrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("webhook", "Webhook"),
                    ("manual", "Manual"),
                    ("push", "New commits"),
                ],
                max_length=16,
            ),
        ),
    ]
