# Generated by Django 5.2.17 on 2026-10-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_incremental_and_check_runs"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="rule_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="reviews_paused",
            field=models.BooleanField(
                default=False, help_text="Set by `/reviewbot ignore`."
            ),
        ),
        migrations.AddField(
            model_name="reviewrun",
            name="config_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="reviewrun",
            name="config_source",
            field=models.CharField(
                blank=True, help_text="dashboard or .reviewbot.yml", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="reviewrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("webhook", "Webhook"),
                    ("manual", "Manual"),
                    ("push", "New commits"),
                    ("command", "PR comment command"),
                ],
                max_length=16,
            ),
        ),
    ]
