# Generated by Django 5.2.17 on 2026-10-06 10:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_rules_config_and_commands"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="dismiss_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("false_positive", "False positive"),
                    ("wont_fix", "Won't fix"),
                    ("duplicate", "Duplicate"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="state",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("accepted", "Accepted"),
                    ("dismissed", "Dismissed"),
                ],
                db_index=True,
                default="open",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="state_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="state_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewrun",
            name="risk_score",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="0-100, deterministic (RE-12).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="post_status",
            field=models.CharField(
                choices=[
                    ("posted", "Posted inline"),
                    ("in_summary", "Listed in summary"),
                    ("below_threshold", "Below severity threshold"),
                    ("low_confidence", "Low confidence"),
                    ("duplicate", "Already posted on this PR"),
                    ("cap_exceeded", "Inline comment cap reached"),
                    ("not_posted", "Not posted (review failed)"),
                    ("category_filtered", "Category excluded by profile"),
                    ("dismissed_earlier", "Dismissed on an earlier run"),
                ],
                default="not_posted",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="FindingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("up", "Helpful"), ("down", "Not helpful")],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="reviews.finding",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("finding", "user"), name="uniq_feedback_per_user"
                    )
                ],
            },
        ),
    ]
