# Generated by Django 5.2.17 on 2026-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_feedback_and_risk"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrun",
            name="cost_usd",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
