# Generated by Django 5.2.17 on 2026-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_run_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="post_status",
            field=models.CharField(
                choices=[
                    ("posted", "Posted inline"),
                    ("in_summary", "Listed in summary"),
                    ("below_threshold", "Below severity threshold"),
                    ("low_confidence", "Low confidence"),
                    ("duplicate", "Already posted on this PR"),
                    ("cap_exceeded", "Inline comment cap reached"),
                    ("not_posted", "Not posted (review failed)"),
                    ("category_filtered", "Category excluded by profile"),
                    ("dismissed_earlier", "Dismissed on an earlier run"),
                    ("merged", "Same issue reported twice in this review"),
                    ("consolidated", "Repeated pattern (grouped in the summary)"),
                ],
                default="not_posted",
                max_length=24,
            ),
        ),
    ]
